EXECUTABLES = helloworld lab1_1 lab1_2 lab1_3 lab1_4

all: $(EXECUTABLES)

helloworld: helloworld.c
	gcc helloworld.c -o helloworld

lab1_1: lab1_1.c
	gcc lab1_1.c -o lab1_1

lab1_2: lab1_2.c
	gcc lab1_2.c -o lab1_2

lab1_3: lab1_3.c
	gcc lab1_3.c -o lab1_3

lab1_4: lab1_4.c
	gcc lab1_4.c -o lab1_4
